
#   IGraph R package
#   Copyright (C) 2014  Gabor Csardi <csardi.gabor@gmail.com>
#   334 Harvard street, Cambridge, MA 02139 USA
#   
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#   
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc.,  51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301 USA
#
###################################################################

## For the future, right now, we do not warn or even message

deprecated <- function(old, new) {
  assign(old, new, envir = asNamespace(packageName()))
}

deprecated("add.edges", add_edges)
deprecated("add.vertex.shape", add_shape)
deprecated("add.vertices", add_vertices)
deprecated("adjacent.triangles", count_triangles)
deprecated("articulation.points", articulation_points)
deprecated("aging.prefatt.game", g_pa_age)
deprecated("aging.ba.game", g_pa_age)
deprecated("aging.barabasi.game", g_pa_age)
deprecated("are.connected", is_connected_to)
deprecated("asymmetric.preference.game", g_pref_asym)
deprecated("autocurve.edges", make_curves)
deprecated("average.path.length", mean_distance)

deprecated("ba.game", g_pa)
deprecated("barabasi.game", g_pa)
deprecated("biconnected.components", biconn_comps)
deprecated("bipartite.mapping", bip_map)
deprecated("bipartite.projection", bip_proj)
deprecated("bipartite.projection.size", bip_proj_size)
deprecated("bipartite.random.game", g_np_bip)
deprecated("blockGraphs", g_blocks)

deprecated("callaway.traits.game", g_traits_callaway)
deprecated("canonical.permutation", canon_perm)
deprecated("clique.number", clique_num)
deprecated("cluster.distribution", comp_dist)
deprecated("clusters", comps)
deprecated("code.length", code_len)
deprecated("cohesive.blocks", cohesive_blocks)
deprecated("connect.neighborhood", connect)
deprecated("contract.vertices", contract)
deprecated("convex.hull", convex_hull)
deprecated("count.multiple", count_multiple)
deprecated("cutat", cut_at)

deprecated("decompose.graph", decompose)
deprecated("degree.sequence.game", g_degseq)
deprecated("delete.edges", delete_edges)
deprecated("delete.vertices", delete_vertices)
deprecated("dendPlot", dend_plot)
deprecated("dendPlot.communities", dend_plot.communities)
deprecated("dendPlot.igraphHRG", dend_plot.igraphHRG)
deprecated("dominator.tree", dominator_tree)
deprecated("dyad.census", dyad_census)

deprecated("edge.connectivity", edge_conn)
deprecated("edge.disjoint.paths", edge_disjoint_paths)
deprecated("establishment.game", g_traits)

deprecated("forest.fire.game", g_forestfire)

deprecated("get.adjedgelist", adj_edge_list)
deprecated("get.adjlist", adj_list)
deprecated("get.adjacency", adj)
deprecated("get.edge.attribute", edge_attr)
deprecated("get.edgelist", edgelist)
deprecated("get.graph.attribute", graph_attr)
deprecated("get.incidence", incidence)
deprecated("get.stochastic", stochastic)
deprecated("get.vertex.attribute", vertex_attr)
deprecated("graph.adhesion", adhesion)
deprecated("graph.adjacency", g_adj_matrix)
deprecated("graph.adjlist", g_adj_list)
deprecated("graph.atlas", g_atlas)
deprecated("graph.automorphisms", automorphisms)
deprecated("graph.bfs", bfs)
deprecated("graph.bipartite", g_bip)
deprecated("graph.cohesion", cohesion)
deprecated("graph.complementer", complementer)
deprecated("graph.compose", compose)
deprecated("graph.coreness", coreness)
deprecated("graph.data.frame", g_df)
deprecated("graph.de.bruijn", g_de_bruijn)
deprecated("graph.disjoint.union", disjoint_union)
deprecated("graph.dfs", dfs)
deprecated("graph.difference", difference)
deprecated("graph.diversity", diversity)
deprecated("graph.edgelist", g_edgelist)
deprecated("graph.eigen", adj_eigen)
deprecated("graph.empty", g_empty)
deprecated("graph.extended.chordal.ring", g_chordal_ring)
deprecated("graph.formula", g_formula)
deprecated("graph.full", g_full)
deprecated("graph.full.bipartite", g_full_bip)
deprecated("graph.full.citation", g_full_cit)
deprecated("graph.graphdb", g_graphdb)
deprecated("graph.incidence", g_incidence)
deprecated("graph.isoclass", iso_class)
deprecated("graph.isocreate", g_iso_class)
deprecated("graph.kautz", g_kautz)
deprecated("graph.knn", knn)
deprecated("graph.laplacian", laplacian)
deprecated("graph.lattice", g_lattice)
deprecated("graph.lcf", g_lcf)
deprecated("graph.maxflow", max_flow)
deprecated("graph.mincut", min_cut)
deprecated("graph.motifs", motifs)
deprecated("graph.motifs.est", sample_motifs)
deprecated("graph.motifs.no", count_motifs)
deprecated("graph.neighborhood", g_ego)
deprecated("graph.star", g_star)
deprecated("graph.strength", strength)
deprecated("graph.tree", g_tree)
deprecated("graph.union", union)
deprecated("graph.ring", g_ring)
deprecated("graphlets.candidate.basis", graphlet_basis)
deprecated("graphlets.project", graphlet_proj)
deprecated("growing.random.game", g_growing)
deprecated("grg.game", g_grg)

deprecated("has.multiple", any_multiple)

deprecated("igraph.arpack.default", arpack_defaults)
deprecated("igraph.console", console)
deprecated("igraph.eigen.default", eigen_defaults)
deprecated("igraph.sample", sample_seq)
deprecated("igraph.version", igraph_version)
deprecated("igraphdemo", igraph_demo)
deprecated("igraphtest", igraph_test)
deprecated("independence.number", ivs_size)
deprecated("independent.vertex.sets", ivs)
deprecated("induced.subgraph", induced_subgraph)
deprecated("interconnected.islands.game", g_islands)

deprecated("k.regular.game", g_k_reg)

deprecated("largest.cliques", largest_cliques)
deprecated("largest.independent.vertex.sets", largest_ivs)
deprecated("lastcit.game", g_last_cit)
deprecated("layout.auto", l_auto)
deprecated("layout.bipartite", l_bip)
deprecated("layout.circle", l_circle)
deprecated("layout.davidson.harel", l_dh)
deprecated("layout.drl", l_drl)
deprecated("layout.fruchterman.reingold", l_fr)
deprecated("layout.gem", l_gem)
deprecated("layout.graphopt", l_graphopt)
deprecated("layout.grid", l_grid)
deprecated("layout.kamada.kawai", l_kk)
deprecated("layout.lgl", l_lgl)
deprecated("layout.mds", l_mds)
deprecated("layout.merge", l_merge)
deprecated("layout.norm", l_norm)
deprecated("layout.random", l_random)
deprecated("layout.reingold.tilford", l_tree)
deprecated("layout.sphere", l_sphere)
deprecated("layout.star", l_star)
deprecated("layout.sugiyama", l_sugiyama)
deprecated("line.graph", g_line)
deprecated("list.edge.attributes", edge_attr_names)
deprecated("list.graph.attributes", graph_attr_names)
deprecated("list.vertex.attributes", vertex_attr_names)

deprecated("maximal.cliques", max_cliques)
deprecated("maximal.cliques.count", num_max_cliques)
deprecated("maximal.independent.vertex.sets", maximal_ivs)
deprecated("minimal.st.separators", min_st_sep)
deprecated("maximum.bipartite.matching", max_bip_match)
deprecated("maximum.cardinality.search", max_cardinality)
deprecated("minimum.size.separators", min_size_sep)
deprecated("minimum.spanning.tree", mst)

deprecated("neighborhood", ego)
deprecated("neighborhood.size", ego_size)
deprecated("no.clusters", count_comps)

deprecated("path.length.hist", distance_table)
deprecated("permute.vertices", permute)
deprecated("piecewise.layout", l_comps)
deprecated("plotHierarchy", plot_hierarchy)
deprecated("power.law.fit", pl_fit)
deprecated("preference.game", g_pref)

deprecated("read.graph", read_graph)
deprecated("remove.edge.attribute", delete_edge_attr)
deprecated("remove.graph.attribute", delete_graph_attr)
deprecated("remove.vertex.attribute", delete_vertex_attr)
deprecated("running.mean", running_mean)

deprecated("sbm.game", g_sbm)
deprecated("scgGrouping", scg_group)
deprecated("scgNormEps", scg_eps)
deprecated("scgSemiProjectors", scg_semi_proj)
deprecated("set.edge.attribute", set_edge_attr)
deprecated("set.graph.attribute", set_graph_attr)
deprecated("set.vertex.attribute", set_vertex_attr)
deprecated("shortest.paths", distances)
deprecated("showtrace", show_trace)
deprecated("stCuts", st_cuts)
deprecated("stMincuts", st_min_cuts)
deprecated("static.fitness.game", g_fitness)
deprecated("statis.power.law.game", g_fitness_pl)

deprecated("tkplot.canvas", tk_canvas)
deprecated("tkplot.center", tk_center)
deprecated("tkplot.close", tk_close)
deprecated("tkplot.export.postscript", tk_postscript)
deprecated("tkplot.fit.to.screen", tk_fit)
deprecated("tkplot.getcoords", tk_coords)
deprecated("tkplot.off", tk_off)
deprecated("tkplot.reshape", tk_reshape)
deprecated("tkplot.rotate", tk_rotate)
deprecated("tkplot.setcoords", tk_set_coords)

deprecated("topological.sort", topo_sort)
deprecated("triad.census", triad_census)

deprecated("unfold.tree", unfold_tree)

deprecated("vertex.connectivity", vertex_conn)
deprecated("vertex.disjoint.paths", vertex_disjoint_paths)

deprecated("watts.strogatz.game", g_smallworld)
deprecated("write.graph", write_graph)
